/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

javafx {
    version = "26-ea+18"
    modules = listOf("javafx.controls", "javafx.fxml")
}

dependencies {
    api("org.hibernate.orm:hibernate-core:7.1.10.Final")
    api("org.springframework.boot:spring-boot-starter:4.0.0")
    api("org.springframework.security:spring-security-crypto:7.0.0")
    api("org.springframework.boot:spring-boot-starter-data-jpa:4.0.0")
    api("io.github.mkpaz:atlantafx-base:2.1.0")
    api("me.paulschwarz:spring-dotenv:4.0.0")
    api("org.springframework.boot:spring-boot-starter-aop:4.0.0-M2")
    runtimeOnly("org.hsqldb:hsqldb:2.7.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:4.0.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

group = "org.quijava"
version = "1.0-SNAPSHOT"
description = "quijava"
java.sourceCompatibility = JavaVersion.VERSION_25

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.withType<Test>() {
    useJUnitPlatform()
    failOnNoDiscoveredTests = false
}
